#!/usr/bin/env node
import assert from "node:assert/strict";
await import("../js/config.js");await import("../js/reactions.js");await import("../js/free-spins.js");await import("../js/payouts.js");await import("../js/game-flow.js");await import("../js/reels.js");
const app=globalThis.CommuneFortune,{CONFIG,GAME_STATES,gameFlow,reels,payouts}=app,FS=app.freeSpins.FREE_SPIN_STATUSES;
function tiers(){CONFIG.lineBets.forEach((_,i)=>{const b=payouts.getTotalBet({lineBetIndex:i});assert.equal(payouts.classifyWinTier(0,b),"none");assert.equal(payouts.classifyWinTier(b*5,b),"nice");assert.equal(payouts.classifyWinTier(b*15,b),"big");assert.equal(payouts.classifyWinTier(b*40,b),"jackpot");});}
function routes(){let spin=0,stop=0,skip=0,start=0,cont=0;const a={onSpin:()=>spin++,onStop:()=>{stop++;return true;},onSkip:()=>skip++,onStart:()=>start++,onContinue:()=>cont++};assert.equal(gameFlow.routePrimaryAction({phase:GAME_STATES.IDLE,...a}),"spun");assert.equal(gameFlow.routePrimaryAction({phase:GAME_STATES.SPINNING,manualStopsEnabled:true,...a}),"stop-requested");assert.equal(gameFlow.routePrimaryAction({phase:GAME_STATES.CELEBRATING,...a}),"skipped");assert.equal(gameFlow.routePrimaryAction({phase:GAME_STATES.BONUS,freeSpinStatus:FS.INTRO,...a}),"started");assert.equal(gameFlow.routePrimaryAction({phase:GAME_STATES.BONUS,freeSpinStatus:FS.SUMMARY,...a}),"continued");assert.equal(gameFlow.routePrimaryAction({phase:GAME_STATES.FREE_SPINS,freeSpinStatus:FS.SPINNING,reelsMoving:true,manualStopsEnabled:true,...a}),"stop-requested");assert.equal(gameFlow.routePrimaryAction({phase:GAME_STATES.FREE_SPINS,freeSpinStatus:FS.PRESENTING,reelsMoving:false,...a}),"skipped");assert.deepEqual({spin,stop,skip,start,cont},{spin:1,stop:2,skip:2,start:1,cont:1});}
function modes(){assert.equal(gameFlow.getPrimaryActionMode({phase:GAME_STATES.IDLE}),"spin");assert.equal(gameFlow.getPrimaryActionMode({phase:GAME_STATES.BONUS,freeSpinStatus:FS.INTRO}),"start");assert.equal(gameFlow.getPrimaryActionMode({phase:GAME_STATES.BONUS,freeSpinStatus:FS.SUMMARY}),"continue");assert.equal(gameFlow.getPrimaryActionMode({phase:GAME_STATES.FREE_SPINS,freeSpinStatus:FS.PRESENTING}),"skip");assert.equal(gameFlow.getPrimaryActionMode({phase:GAME_STATES.FREE_SPINS,freeSpinStatus:FS.SPINNING,reelsMoving:true,manualStopsEnabled:true,nextStopIndex:1}),"stop");assert.equal(gameFlow.getStopAriaLabel(1),"Stop reel 2");}
function queue(){const c=reels.createManualStopState({enabled:true});c.begin(0);assert.deepEqual([c.requestNextStop(1).reelIndex,c.requestNextStop(2).reelIndex,c.requestNextStop(3).reelIndex],[0,1,2]);assert.equal(c.requestNextStop(4).accepted,false);assert.equal(c.snapshot().requestedStops,3);}
function manualIsolation(){const common={targetStops:[7,4,5],state:{lineBetIndex:0,fortuneMeter:{value:100,charged:true}},id:"m",createdAt:"t",featureRolls:{expandingWild:{roll:0}}};const a=payouts.createSpinResult({...common,featureFlags:{...CONFIG.features,manualStops:false,freeSpins:false}}),b=payouts.createSpinResult({...common,featureFlags:{...CONFIG.features,manualStops:true,freeSpins:false}});for(const k of ["originalMatrix","resolvedMatrix","featureRolls","transformations","lineWins","combinationWins","fortuneMeterAward","totalWin","winTier"])assert.deepEqual(a[k],b[k]);}
function reduced(){assert.ok(gameFlow.getCelebrationDuration("nice",{reducedMotion:true})<gameFlow.getCelebrationDuration("nice"));assert.ok(gameFlow.getCelebrationDuration("nice",{compact:true})<gameFlow.getCelebrationDuration("nice"));const r=app.reactions.selectReaction({totalWin:30,winTier:"nice",lineWins:[{symbolKey:"STR",payout:30}],combinationWins:[]},{compact:true,reducedMotion:true});assert.equal(r.compact,true);assert.equal(r.reducedMotion,true);}
[tiers,routes,modes,queue,manualIsolation,reduced].forEach(t=>t());console.log("Presentation tests: PASS (6 groups)");
